### ISSUE TITLE
Add compose-like chain function?

### ISSUE THREAD

**Issue by ricokahler** [ricokahler/color2k#15]
Polished and chroma have APIs that let these functions be chained together to do many color manipulation operations on one color.

chroma-js uses objects

```js
chroma('pink').darken().saturate(2).hex()
```

and polished js API curries every function so that you can compose them

```js
import { compose } from 'ramda' // Replace with any compose() function of your choice
import { lighten, desaturate } from 'polished'

// Create tone() helper
const tone = compose(lighten(0.1), desaturate(0.1))
```

---

Here's the ask/question:

If you've used those libs before: **How often have you chain together multiple color functions together?** Is it a use-case that this lib should provide some code for?

**Please upvote 👍 or comment to provide feedback.**

I have a [PR that implements this](https://github.com/ricokahler/color2k/pull/14) with minimal code, I'm just wondering if people will use it.

**Comment by subzey** [comment]
The chaining ("fluent") style has one inherent flaw: to make it possible, all the methods should present in the proto or be mixed in. Ether way it's not tree-shakable.

So you have to bundle all the code into to prod, even if you're not going to use it.

There's nothing too bad in calling
```js
lighten(desaturate(c, .1), .1)
```

`compose` or `|>` or whatever can always be applied. Treeshakability can not

**Comment by ricokahler** [comment]
@subzey I totally agree. I haven't seen much feedback in this issue so it's probably not gonna land in the final API. In my personal usage of this lib and others like it, I've never really needed to chain more than one or two functions anyway.

If you were wondering how I was planning on adding this feature, take a look at #14 (feel free to leave feedback) . The fluent API would definitely be a no-go though.
