### ISSUE TITLE
[newFeature] getDifferenceColor

### ISSUE THREAD

**Issue by Daniel4Digital** [ricokahler/color2k#216]
Hi there,

Would be great to have a library where we could first check the difference between 2 colors.

Let say: ('#EDF0FC', '#B2C3F9'), that would generate a value or object where we could then pass to another function that would have the new color let say we pass the same ('#EDF0FC'), it should return the "#B2C3F9" color;

If we pass: '#1CA085' it should return '#007382'. So basically we would have the same difference applied to a new color.
With that in mind, with 1 single color I can calculate many others variations automatically.

**Comment by ricokahler** [comment]
Hi @Daniel4Digital 👋

Thanks for the suggestion however, due the philosophy of this lib (i.e. lean and small bundle), this is not a good candidate feature for this lib.

However, if you have have a stackoverflow account, I'd be happy to assist you in implementing a function that does this over there.

Feel free to link your question here and I'll try my best to answer it.
