### ISSUE TITLE
toHex sometimes returns the wrong color

### ISSUE THREAD

**Issue by jafaircl** [ricokahler/color2k#235]
The 2 specific examples I've seen are:

```typescript
// #b00020 is a red
toHex(darken('#b00020', 0.2)) // returns #4d00e0 (a purple) instead of #7D0000
// this one seems to just switch the first 2 numbers
toHex('#03dac5') // returns #30dac5
```

I got the correct values from [this tool](https://www.hexcolortool.com/). Here is a [stackblitz](https://stackblitz.com/edit/typescript-qvhjwr) where you can see the issue.

For the first one, if you drop the darkening factor to 0.18, it returns a red.

This may be related somehow to #211

**Comment by ricokahler** [comment]
Thanks for this report and the reproduction!

For now I've opened up a PR with a failing test of your reproduction. I should have a fix out within 24 hours.

**Comment by ricokahler** [comment]
sigh lol https://github.com/ricokahler/color2k/pull/236/commits/51bca74ac4ccfe854cc2711923403647868a467b

thanks for the report! this is release in 1.1.1

**Comment by jafaircl** [comment]
Well at least it was an easy fix. Thanks!
