### ISSUE TITLE
Documentation improvements (hasBadContrast, opacify, transparentize)

### ISSUE THREAD

**Issue by diondiondion** [ricokahler/color2k#244]
Hi Rico, thanks for creating this library, great work! I'm currently in the process of migrating to color2k from chromaJS and the process has been very smooth.

Some parts of the documentation confused me, though:

1. `opacify`, `transparentize`:
    The description of the `amount` parameter seems to have been copied & pasted from the `darken` function, should probably be changed to "the amount to increase the opacity/transparency by, given as a decimal between 0 and 1"
2. `hasBadContrast`:
    Here it's more the function API that's confusing me, and the documentation didn't help much. How can a single colour have bad contrast; what's the "background colour"? (I just checked out the implementation, apparently it's white! 😅 )
    It would be useful to clarify this in the docs. It also seems to me like the function would be much more useful with a third parameter to specify the base colour, but luckily it's easy enough to write your own wrapper around `getContrast`.

Thanks for reading :)

**Comment by ricokahler** [comment]
incredible thank you
