### ISSUE TITLE
Put color2k in scope at color2k.com

### ISSUE THREAD

**Issue by StevenBlack** [ricokahler/color2k#32]
Hi 👋 — good lib!

**A suggestion**:  did you know... you can go to [the momentjs website](https://momentjs.com/), open the debug console and play with `moment()` and all its facets?  The same is true on [the lodash website](https://lodash.com/)!

This is very handy!  I was hoping to play with color2k in-situ, but no go.  The code sandbox is, honestly, a convoluted bridge too far, and takes the user away from the best sandbox, a console sesh using your own site.

Example from the console when I'm on the Lodash website:

![2020-05-17_16-58-32](https://user-images.githubusercontent.com/80144/82160029-6363f900-9860-11ea-85b7-a87bc2d87250.jpg)

**Comment by ricokahler** [comment]
Not a bad idea. I think I’ll do later today!

**Comment by StevenBlack** [comment]
Is this implemented @ricokahler?  if so, it's not working.

Here's my use case:

![2020-05-17_22-51-33](https://user-images.githubusercontent.com/80144/82170021-45fb5300-9891-11ea-8aa3-c9476d26a2b8.jpg)

**Comment by ricokahler** [comment]
@StevenBlack it is, it's just under the global `color2k` to prevent naming collisions. The lodash examples you sent also does this.

![image](https://user-images.githubusercontent.com/10551026/82170089-75aa5b00-9891-11ea-92d1-d563f4f85cab.png)

**Comment by StevenBlack** [comment]
ah!  Makes sense.  Thanks!
