### ISSUE TITLE
IsDark and isLight support? I can not find

### ISSUE THREAD

**Issue by meftunca** [ricokahler/color2k#372]
Maybe it will work for your project ...

```ts
import { parseToRgba } from "color2k";

const isDark = (color: string) => {
  let rgb = parseToRgba(color);
  let yiq = (rgb[0] * 299 + rgb[1] * 587 + rgb[2] * 114) / 1000;
  return yiq < 128;
}
```

**Comment by ricokahler** [comment]
Hi @meftunca, apparently I missed this when you posted it back in may but I believe `isDark` and `isLight` is analogous to the current [`readableColorIsBlack`](https://color2k.com/#readable-color-is-black) function and [`hasBadContrast`](https://color2k.com/#has-bad-contrast).

These functions use [`getLuminance`](https://color2k.com/#get-luminance) internally to return the correct value according to accessibility guidelines from W3C.

You could implement isDark and isLight as follows:

```js
import { readableColorIsBlack } from 'color2k';

const isDark = (color) => !readableColorIsBlack(color);
const isLight = (color) => readableColorIsBlack(color);
```

Feel free to comment if this is not what you're looking for :D
