### ISSUE TITLE
[Feature] add support for hex8

### ISSUE THREAD

**Issue by lukasoppermann** [ricokahler/color2k#453]
Maybe by adding a new function `toHex8` that outputs the hex value with transparency.

**Comment by ricokahler** [comment]
This library does support outputting to hex8 but only when the alpha value is less than one. For the sake of keeping the API stable, I'll close this one for now.

https://github.com/ricokahler/color2k/blob/a16e5023156ad246dc45b48928266cad3a3ba79b/src/toHex.test.ts#L17

**Comment by lukasoppermann** [comment]
Ahh, nice, maybe you could add this to the description of toHex?
