### ISSUE TITLE
Using `toHex` with `hsla` where `a = 0` leads to a result with alpha=1

### ISSUE THREAD

**Issue by six7** [ricokahler/color2k#463]
When you're using `toHex("hsla(15, 50%, 50%, 0)")`

you'll get `#bf6040`

which is the same as when using `1` as alpha.

What I'd expect is that I get the 8-digit hex with 0 opacity `#bf604000`

When I use any value that is not 0 it gives me the expected result

Codesandbox: https://codesandbox.io/s/vigilant-meadow-4q4wj5?file=/src/index.js

**Comment by ricokahler** [comment]
Thanks for opening the issue!

**Comment by six7** [comment]
Amazing, thank you!
