### ISSUE TITLE
Breaks in the latest webkit version

### ISSUE THREAD

**Issue by lukasmasuch** [ricokahler/color2k#487]
`color2k` doesn't work with the latest version of webkit. You can reproduce this by installing the [Safari Technology Preview](https://developer.apple.com/safari/resources/) and going to [this demo](https://codesandbox.io/p/sandbox/color2k-demos-8vjh3?file=%2Fsrc%2FApp.tsx%3A150%2C1-153%2C1) or running `color2k.transparentize("red")` within the dev console on https://color2k.com

<img width="1126" alt="image" src="https://github.com/ricokahler/color2k/assets/2852129/b68e58a6-d93b-415d-844b-3c64ed54db6f">

<img width="316" alt="image" src="https://github.com/ricokahler/color2k/assets/2852129/5ae68fc6-8d8c-46fb-8022-13ba2211dc02">

**Comment by kmcgrady** [comment]
Following up on this. We have determined that `Array.from` in the TP version is not filling in values of `undefined. [It looks like it has since been fixed](https://github.com/WebKit/WebKit/commit/c68cf48dd75cff6ed634b66127a0bbf13ef913bb), and will be released in a future version.

**Comment by moeriki** [comment]
Seems fixed in STP release of 7-dec.

**Comment by danielbuechele** [comment]
I'm running into this issue, too. Is this something that can be worked around in this library?

**Comment by yassinebelkacemi-r** [comment]
Hi thanks for the fix! When will this be included in the playwright package?
